services:
  database:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql_server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "VeryLongPassword69$" 
      MSSQL_PID: "Developer"
    user: root
    ports:
      - "1433:1433"
    volumes:
      - ./database/StackOverflowMini.bak:/var/opt/mssql/StackOverflowMini.bak
      - ./database/init-db.sql:/var/opt/mssql/init-db.sql
      - ./database/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      - app-net
    restart: unless-stopped
    tty: true
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "VeryLongPassword69$" -C -Q "SELECT name FROM sys.databases WHERE name = 'StackOverflowMini'" | grep -q "StackOverflowMini" || exit 1
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 30s

  directus-master:
    image: directus/directus:11
    container_name: directus-master
    ports:
      - "8055:8055"
    environment:
      KEY: "uD4sL9pA2vF8jN5kR1wG3bH6yC7xZ0qT" 
      SECRET: "mB1oI5eW9aV3kH7rT4zL8pD2fN6jG0uC"
      ADMIN_TOKEN: "CUuaxLbnkBkI2dfDhn1NyFRGmNFo6i3c"
      DB_CLIENT: "mssql"
      DB_HOST: "mssql_server"
      DB_PORT: "1433"
      DB_DATABASE: "StackOverflowMini"
      DB_USER: "sa"
      DB_PASSWORD: "VeryLongPassword69$" # Diubah
      ADMIN_EMAIL: "admin@mail.com"
      ADMIN_PASSWORD: "admin" # Diubah
      PORT: "8055"
      TRUSTED_PROXIES: "0.0.0.0/0"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://directus-master:8055/server/health"]
      interval: 300s
      timeout: 300s
      retries: 15
      start_period: 120s
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-net
    restart: unless-stopped

  directus-slave:
    image: directus/directus:11
    container_name: directus-slave
    ports:
      - "8066:8066"
    environment:
      KEY: "uD4sL9pA2vF8jN5kR1wG3bH6yC7xZ0qT" 
      SECRET: "mB1oI5eW9aV3kH7rT4zL8pD2fN6jG0uC"
      ADMIN_TOKEN: "CUuaxLbnkBkI2dfDhn1NyFRGmNFo6i3c"
      DB_CLIENT: "mssql"
      DB_HOST: "mssql_server"
      DB_PORT: "1433"
      DB_DATABASE: "StackOverflowMini"
      DB_USER: "sa"
      DB_PASSWORD: "VeryLongPassword69$" # Diubah
      ADMIN_EMAIL: "admin@mail.com"
      ADMIN_PASSWORD: "admin" # Diubah
      PORT: "8066"
      TRUSTED_PROXIES: "0.0.0.0/0"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://directus-slave:8066/server/health"]
      interval: 300s
      timeout: 300s
      retries: 15
      start_period: 120s
    depends_on:
      database:
        condition: service_healthy
      directus-master:
        condition: service_healthy
    networks:
      - app-net
    restart: unless-stopped
  #
  # app2:
  #   image: directus/directus:latest
  #   container_name: app_server_2
  #   ports:
  #     - "8057:8055"
  #   environment:
  #     KEY: "uD4sL9pA2vF8jN5kR1wG3bH6yC7xZ0qT"
  #     SECRET: "mB1oI5eW9aV3kH7rT4zL8pD2fN6jG0uC"
  #     DB_CLIENT: "mssql"
  #     DB_HOST: "database"
  #     DB_PORT: "1433"
  #     DB_DATABASE: "StackOverflow2010"
  #     DB_USER: "sa"
  #     DB_PASSWORD: "PulauJawaBesar1234" # Diubah
  #     ADMIN_EMAIL: "admin@x.com"
  #     ADMIN_PASSWORD: "PulauJawaBesar1234" # Diubah
  #   depends_on:
  #     - database
  #   networks:
  #     - app-net
  #   restart: unless-stopped
  #
  # loadbalancer:
  #   image: haproxy:lts-alpine
  #   container_name: load_balancer
  #   ports:
  #     - "8080:8080"
  #     - "8404:8404"
  #   volumes:
  #     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  #   depends_on:
  #     - app1
  #     - app2
  #   networks:
  #     - app-net
  #   restart: unless-stopped

  loadbalancer:
    image: caddy:2.10.0-alpine
    container_name: load_balancer
    ports:
      - "8080:80"
      - "8888:8888"
      - "2019:2019"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - .:/srv:ro
    depends_on:
      database:
        condition: service_healthy
      directus-master:
        condition: service_healthy
      directus-slave:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-net
    restart: unless-stopped

  k6:
    build:
      context: ./xk6-dashboard
      dockerfile: Dockerfile
    container_name: k6
    volumes:
      - ./k6/scripts:/scripts
      - ./k6/outputs:/outputs
    working_dir: /scripts
    environment:
      K6_WEB_DASHBOARD_HOST: "0.0.0.0"
      K6_WEB_DASHBOARD_PORT: "5665"
    ports:
      - "5665:5665"
    tty: true
    networks:
      - app-net
    depends_on:
      database:
        condition: service_healthy
      directus-master:
        condition: service_healthy
      directus-slave:
        condition: service_healthy
      loadbalancer:
        condition: service_healthy

networks:
  app-net:
